language: node_js
node_js:
- iojs
- '7'
script: npm test
deploy:
  provider: heroku
  api_key:
    secure: LtksyUU6R/ftsgusWeymkiGzp2U2kCpq/WDWCc8+ctfD4246xJEDjDYgvx9XjmTofZzzafqgCEQBU+O2LjTuO/delFI2yEw1VReKrMKZcu95sCr9jelDXl9j8Udwb1chA2ikxUl1JXQ+fQFYUOUAg0aPT0K/FLMhNzJFY5e8qjr9NcMD0UM/q91rcmWJWS0bHivY2DcQSvYPLd0kHl9GNi71XYXRgeR107+vNQjcVMbX2nlOOIedcILa1yDcsApAp0aQrOEVKBCOhdOz0AGVg4zBeqfQ2s0Y2aMqSRTKo6H4PiCQRyJG7eo3fO7THo6XCUbOEw/XN4jJ0XUBwl/gIQxPYAQgnHNbP0gSWgcnBDQFGOi7QHtQd84n95xlN0jGn95TobQYz1qSxgqlJaF1HoQtBgUmfpHJoBy2dyuz3uZlKF1T3O8Ts2/W9jrKyhu6fUCw4DzkNZQy5z0tKXfyhI5k9yykraIlG2ujXdJsELTMq2wUYy9EqcCCKgV5m3nchnj12iZm7OF3hX+JSPoyrdOTEr3yu13+OmbiCqzZ0kz4Erkj0YXDoubZbgcSSSvwIZ82nzYr46nSGw1R0X24YT36ouRJnfji6vhv9omST7cf1pqSqaB5uKRYy3l0DB7iKgXzy4+NSr6Ojnu0RldiVRdk0RLXy/UGd2cKWjsv70M=
install: true